# 3.Indexing and Filtering

## Indexing and Filterong

- Access just certain rows or columns
- loc & iloc
- using string contains

## 3.1 Direct Filtering with Square Brackets

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\projects\pluralsight\collection\Cleaning Data Python Data Playbook\artwork_data.csv')

c:\program files\python38\lib\site-packages\IPython\core\interactiveshell.py:3062: DtypeWarning: Columns (9,13) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [4]:
df.head()

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
2,1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785,1922.0,support: 343 x 467 mm,343,467,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
3,1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 318 x 394 mm,318,394,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826,1919.0,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...

In [5]:
df['id']

0          1035
1          1036
2          1037
3          1038
4          1039
          ...
69196    122960
69197    122961
69198    121181
69199    112306
69200    127035
Name: id, Length: 69201, dtype: int64

In [6]:
df['id'][1]

1036

In [7]:
df[['artist', 'title']]

                   artist                                              title
0           Blake, Robert  A Figure Bowing before a Seated Old Man with h...
1           Blake, Robert  Two Drawings of Frightened Figures, Probably f...
2           Blake, Robert  The Preaching of Warning. Verso: An Old Man En...
3           Blake, Robert     Six Drawings of Figures with Outstretched Arms
4          Blake, William  The Circle of the Lustful: Francesca da Rimini...
...                   ...                                                ...
69196  P-Orridge, Genesis                        Larvae (from Tampax Romana)
69197  P-Orridge, Genesis                   Living Womb (from Tampax Romana)
69198        Hatoum, Mona                                      Present Tense
69199       Creed, Martin          Work No. 227: The lights going on and off
69200   Brunias, Agostino                   Dancing Scene in the West Indies

[69201 rows x 2 columns]

In [8]:
df[['artist', 'title']][:,1]

TypeError: '(slice(None, None, None), 1)' is an invalid key

In [9]:
df[1:2]#rows

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...

In [10]:
df[1:5]

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
2,1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785,1922.0,support: 343 x 467 mm,343,467,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
3,1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 318 x 394 mm,318,394,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826,1919.0,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...

In [11]:
df[2:5]['artist']

2     Blake, Robert
3     Blake, Robert
4    Blake, William
Name: artist, dtype: object

In [13]:
df['year'] = pd.to_numeric(df.year, errors='coerce')
df[df['year'] > 1800]

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919.0,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
5,1040,A00006,"Blake, William",artist,39,Ciampolo the Barrator Tormented by the Devils,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919.0,image: 240 x 338 mm,240,338,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-ciam...
6,1041,A00007,"Blake, William",artist,39,The Baffled Devils Fighting,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919.0,image: 242 x 334 mm,242,334,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
7,1042,A00008,"Blake, William",artist,39,The Six-Footed Serpent Attacking Agnolo Brunel...,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919.0,image: 246 x 340 mm,246,340,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
8,1043,A00009,"Blake, William",artist,39,The Serpent Attacking Buoso Donati,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919.0,image: 241 x 335 mm,241,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69195,122959,T13864,"P-Orridge, Genesis",artist,16646,It’s That Time Of The Month (from Tampax Romana),1975,"Wood, Perspex, clock case, tampons and human b...",Transferred from Tate Archive 2012,1975.0,2013.0,object: 305 x 305 x 135 mm,305,305,135.0,mm,NaN,© Genesis P-Orridge,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/p-orridge-...
69196,122960,T13865,"P-Orridge, Genesis",artist,16646,Larvae (from Tampax Romana),1975,"Perspex, Wood, hairpiece, tampon and human blood",Transferred from Tate Archive 2012,1975.0,2013.0,object: 305 x 305 x 135 mm,305,305,135.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/p-orridge-...
69197,122961,T13866,"P-Orridge, Genesis",artist,16646,Living Womb (from Tampax Romana),1976,"Wood, Perspex, plastic, photograph on paper, t...",Transferred from Tate Archive 2012,1976.0,2013.0,object: 305 x 305 x 135 mm,305,305,135.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/p-orridge-...
69198,121181,T13867,"Hatoum, Mona",artist,2365,Present Tense,1996,Soap and glass beads,Presented by Tate Members 2013,1996.0,2013.0,displayed: 45 x 2410 x 2990 mm,45,2410,2990.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/hatoum-pre...
69199,112306,T13868,"Creed, Martin",artist,2760,Work No. 227: The lights going on and off,2000,Gallery lighting,"Purchased with funds provided by Tate Members,...",2000.0,2013.0,Overall display dimensions variable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/creed-work...

## 3.2 Using .loc

In [14]:
#df.loc[ROWS, COLS]

NameError: name 'ROWS' is not defined

In [15]:
df.loc[0,:]

id                                                                 1035
accession_number                                                 A00001
artist                                                    Blake, Robert
artistRole                                                       artist
artistId                                                             38
title                 A Figure Bowing before a Seated Old Man with h...
dateText                                                 date not known
medium                Watercolour, ink, chalk and graphite on paper....
creditLine                          Presented by Mrs John Richmond 1922
year                                                                NaN
acquisitionYear                                                    1922
dimensions                                        support: 394 x 419 mm
width                                                               394
height                                                              419
depth                                                               NaN
units                                                                mm
inscription                                                         NaN
thumbnailCopyright                                                  NaN
thumbnailUrl          http://www.tate.org.uk/art/images/work/A/A00/A...
url                   http://www.tate.org.uk/art/artworks/blake-a-fi...
Name: 0, dtype: object

In [16]:
# different to square bracket search becaus they include the last position, loc works by label and []by index
df.loc[0:2,:]

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
2,1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785.0,1922.0,support: 343 x 467 mm,343,467,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...

In [17]:
df.loc[0:2, 'title']

0    A Figure Bowing before a Seated Old Man with h...
1    Two Drawings of Frightened Figures, Probably f...
2    The Preaching of Warning. Verso: An Old Man En...
Name: title, dtype: object

In [18]:
df.loc[0:2,['artist', 'title']]

          artist                                              title
0  Blake, Robert  A Figure Bowing before a Seated Old Man with h...
1  Blake, Robert  Two Drawings of Frightened Figures, Probably f...
2  Blake, Robert  The Preaching of Warning. Verso: An Old Man En...

In [20]:
df.loc[[1,5,25],['artist', 'title']]

            artist                                              title
1    Blake, Robert  Two Drawings of Frightened Figures, Probably f...
5   Blake, William      Ciampolo the Barrator Tormented by the Devils
25  Blake, William                             Behemoth and Leviathan

In [21]:
df.loc[[1,5],'id':'artist']

     id accession_number          artist
1  1036           A00002   Blake, Robert
5  1040           A00006  Blake, William

In [22]:
df.loc[df.artist == 'Blake, Robert', :]

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
2,1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785.0,1922.0,support: 343 x 467 mm,343,467,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
3,1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 318 x 394 mm,318,394,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...

## 3.3 Using iloc

In [23]:
df.head()

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
2,1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785.0,1922.0,support: 343 x 467 mm,343,467,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
3,1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 318 x 394 mm,318,394,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919.0,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...

In [24]:
df.iloc[0,:]

id                                                                 1035
accession_number                                                 A00001
artist                                                    Blake, Robert
artistRole                                                       artist
artistId                                                             38
title                 A Figure Bowing before a Seated Old Man with h...
dateText                                                 date not known
medium                Watercolour, ink, chalk and graphite on paper....
creditLine                          Presented by Mrs John Richmond 1922
year                                                                NaN
acquisitionYear                                                    1922
dimensions                                        support: 394 x 419 mm
width                                                               394
height                                                              419
depth                                                               NaN
units                                                                mm
inscription                                                         NaN
thumbnailCopyright                                                  NaN
thumbnailUrl          http://www.tate.org.uk/art/images/work/A/A00/A...
url                   http://www.tate.org.uk/art/artworks/blake-a-fi...
Name: 0, dtype: object

In [25]:
df.iloc[0:3,:]# exclusive on the last number

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
2,1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785.0,1922.0,support: 343 x 467 mm,343,467,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...

In [26]:
df.loc[0:3,:]

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
2,1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785.0,1922.0,support: 343 x 467 mm,343,467,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
3,1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 318 x 394 mm,318,394,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...

In [28]:
df.set_index('id', inplace=True)

In [29]:
df.head()

,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
id,,,,,,,,,,,,,,,,,,,
1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785.0,1922.0,support: 343 x 467 mm,343,467,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 318 x 394 mm,318,394,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919.0,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...

In [30]:
df.iloc[0:3,:]

,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
id,,,,,,,,,,,,,,,,,,,
1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785.0,1922.0,support: 343 x 467 mm,343,467,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...

In [31]:
df.loc[0:3,:]

KeyError: 0

In [32]:
df.iloc[0:3,0:3]

     accession_number         artist artistRole
id
1035           A00001  Blake, Robert     artist
1036           A00002  Blake, Robert     artist
1037           A00003  Blake, Robert     artist

In [33]:
df.reset_index(inplace=True)

In [34]:
df

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
2,1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785.0,1922.0,support: 343 x 467 mm,343,467,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
3,1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 318 x 394 mm,318,394,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919.0,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69196,122960,T13865,"P-Orridge, Genesis",artist,16646,Larvae (from Tampax Romana),1975,"Perspex, Wood, hairpiece, tampon and human blood",Transferred from Tate Archive 2012,1975.0,2013.0,object: 305 x 305 x 135 mm,305,305,135.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/p-orridge-...
69197,122961,T13866,"P-Orridge, Genesis",artist,16646,Living Womb (from Tampax Romana),1976,"Wood, Perspex, plastic, photograph on paper, t...",Transferred from Tate Archive 2012,1976.0,2013.0,object: 305 x 305 x 135 mm,305,305,135.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/p-orridge-...
69198,121181,T13867,"Hatoum, Mona",artist,2365,Present Tense,1996,Soap and glass beads,Presented by Tate Members 2013,1996.0,2013.0,displayed: 45 x 2410 x 2990 mm,45,2410,2990.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/hatoum-pre...
69199,112306,T13868,"Creed, Martin",artist,2760,Work No. 227: The lights going on and off,2000,Gallery lighting,"Purchased with funds provided by Tate Members,...",2000.0,2013.0,Overall display dimensions variable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/creed-work...
69200,127035,T13869,"Brunias, Agostino",artist,3824,Dancing Scene in the West Indies,1764–96,Oil paint on canvas,Purchased with assistance from Tate Patrons an...,1764.0,2013.0,unconfirmed: 508 x 660 mm,508,660,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/brunias-da...

In [35]:
df.iloc[0:3,0:3]

     id accession_number         artist
0  1035           A00001  Blake, Robert
1  1036           A00002  Blake, Robert
2  1037           A00003  Blake, Robert

## 3.4 Filtering data with str.contains

In [78]:
df = pd.read_csv(r'C:\projects\pluralsight\collection\Cleaning Data Python Data Playbook\artwork_data.csv')
df['year'] = pd.to_numeric(df.year, errors='coerce')

In [46]:
df.medium

0        Watercolour, ink, chalk and graphite on paper....
1                                        Graphite on paper
2              Graphite on paper. Verso: graphite on paper
3                                        Graphite on paper
4                                  Line engraving on paper
                               ...
69196     Perspex, Wood, hairpiece, tampon and human blood
69197    Wood, Perspex, plastic, photograph on paper, t...
69198                                 Soap and glass beads
69199                                     Gallery lighting
69200                                  Oil paint on canvas
Name: medium, Length: 69201, dtype: object

In [47]:
type(df.medium)

pandas.core.series.Series

In [48]:
df.medium.str

In [56]:
df.medium.str.contains('Graphite')

0        False
1         True
2         True
3         True
4        False
         ...
69196    False
69197    False
69198    False
69199    False
69200    False
Name: medium, Length: 69201, dtype: object

In [64]:
df.loc[df.medium.str.contains('Graphite', na=False), ['artist','medium']]

,artist,medium
1,"Blake, Robert",Graphite on paper
2,"Blake, Robert",Graphite on paper. Verso: graphite on paper
3,"Blake, Robert",Graphite on paper
32,"Blake, William",Graphite on paper. Verso: graphite on paper
39,"Blake, William",Graphite on paper. Verso: graphite on paper
...,...,...
69092,"Constable, John",Graphite on paper
69129,"Takamatsu, Jiro",Graphite on paper
69139,"Horn, Rebecca","Graphite, coloured graphite and acrylic paint ..."
69140,"Horn, Rebecca","Graphite, coloured graphite and acrylic paint ..."
69154,"Hepworth, Dame Barbara","Graphite, watercolour, crayon and oil paint on..."

In [65]:
df.loc[df.medium.str.contains('Graphite', na=False, case=False), ['artist','medium']]

,artist,medium
0,"Blake, Robert","Watercolour, ink, chalk and graphite on paper...."
1,"Blake, Robert",Graphite on paper
2,"Blake, Robert",Graphite on paper. Verso: graphite on paper
3,"Blake, Robert",Graphite on paper
32,"Blake, William",Graphite on paper. Verso: graphite on paper
...,...,...
69140,"Horn, Rebecca","Graphite, coloured graphite and acrylic paint ..."
69154,"Hepworth, Dame Barbara","Graphite, watercolour, crayon and oil paint on..."
69155,"Hepworth, Dame Barbara","Oil paint, watercolour, crayon and graphite on..."
69156,"Hepworth, Dame Barbara","Oil paint, watercolour, crayon and graphite on..."
69157,"Hepworth, Dame Barbara",Oil paint and graphite on paper

In [66]:
df.loc[df.medium.str.contains('(?i)Graphite', na=False, case=False, regex=True), ['artist','medium']]

,artist,medium
0,"Blake, Robert","Watercolour, ink, chalk and graphite on paper...."
1,"Blake, Robert",Graphite on paper
2,"Blake, Robert",Graphite on paper. Verso: graphite on paper
3,"Blake, Robert",Graphite on paper
32,"Blake, William",Graphite on paper. Verso: graphite on paper
...,...,...
69140,"Horn, Rebecca","Graphite, coloured graphite and acrylic paint ..."
69154,"Hepworth, Dame Barbara","Graphite, watercolour, crayon and oil paint on..."
69155,"Hepworth, Dame Barbara","Oil paint, watercolour, crayon and graphite on..."
69156,"Hepworth, Dame Barbara","Oil paint, watercolour, crayon and graphite on..."
69157,"Hepworth, Dame Barbara",Oil paint and graphite on paper

In [76]:
df.loc[df.medium.str.contains('(?i)Graphite', na=False, regex=True) | df.medium.str.contains('(?i)Line', na=False, regex=True), ['artist','medium']]

,artist,medium
0,"Blake, Robert","Watercolour, ink, chalk and graphite on paper...."
1,"Blake, Robert",Graphite on paper
2,"Blake, Robert",Graphite on paper. Verso: graphite on paper
3,"Blake, Robert",Graphite on paper
4,"Blake, William",Line engraving on paper
...,...,...
69140,"Horn, Rebecca","Graphite, coloured graphite and acrylic paint ..."
69154,"Hepworth, Dame Barbara","Graphite, watercolour, crayon and oil paint on..."
69155,"Hepworth, Dame Barbara","Oil paint, watercolour, crayon and graphite on..."
69156,"Hepworth, Dame Barbara","Oil paint, watercolour, crayon and graphite on..."
69157,"Hepworth, Dame Barbara",Oil paint and graphite on paper

In [74]:
df.loc[df.medium.str.contains('Graphite|Line' , na=False, case=False, regex=True), ['artist','medium']]

,artist,medium
0,"Blake, Robert","Watercolour, ink, chalk and graphite on paper...."
1,"Blake, Robert",Graphite on paper
2,"Blake, Robert",Graphite on paper. Verso: graphite on paper
3,"Blake, Robert",Graphite on paper
4,"Blake, William",Line engraving on paper
...,...,...
69140,"Horn, Rebecca","Graphite, coloured graphite and acrylic paint ..."
69154,"Hepworth, Dame Barbara","Graphite, watercolour, crayon and oil paint on..."
69155,"Hepworth, Dame Barbara","Oil paint, watercolour, crayon and graphite on..."
69156,"Hepworth, Dame Barbara","Oil paint, watercolour, crayon and graphite on..."
69157,"Hepworth, Dame Barbara",Oil paint and graphite on paper

In [79]:
df.dtypes

id                      int64
accession_number       object
artist                 object
artistRole             object
artistId                int64
title                  object
dateText               object
medium                 object
creditLine             object
year                  float64
acquisitionYear       float64
dimensions             object
width                  object
height                 object
depth                 float64
units                  object
inscription            object
thumbnailCopyright     object
thumbnailUrl           object
url                    object
dtype: object

In [80]:
#str methodes in columns tat aren t str

In [81]:
df.year.astype(str).str.contains('1826')

0        False
1        False
2        False
3        False
4         True
         ...
69196    False
69197    False
69198    False
69199    False
69200    False
Name: year, Length: 69201, dtype: bool

In [82]:
df.loc[df.year.astype(str).str.contains('1826')]

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919.0,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
5,1040,A00006,"Blake, William",artist,39,Ciampolo the Barrator Tormented by the Devils,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919.0,image: 240 x 338 mm,240,338,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-ciam...
6,1041,A00007,"Blake, William",artist,39,The Baffled Devils Fighting,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919.0,image: 242 x 334 mm,242,334,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
7,1042,A00008,"Blake, William",artist,39,The Six-Footed Serpent Attacking Agnolo Brunel...,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919.0,image: 246 x 340 mm,246,340,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
8,1043,A00009,"Blake, William",artist,39,The Serpent Attacking Buoso Donati,"1826–7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826.0,1919.0,image: 241 x 335 mm,241,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61797,20100,T06372,"Turner, Joseph Mallord William",after,558,"Scarborough, engraved by T. Lupton",published 1826,Engraving on paper,Transferred from the British Museum 1988,1826.0,1988.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.tate.org.uk/art/images/work/T/T06/T...,http://www.tate.org.uk/art/artworks/turner-sca...
62313,21186,T06898,"Danby, Francis",after,135,"Sunset at Sea after a Storm, engraved by F.C. ...",1826,Mezzotint on paper,Purchased 1994,1826.0,1994.0,image: 189 x 305 mm,189,305,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/T/T06/T...,http://www.tate.org.uk/art/artworks/danby-suns...
63511,22319,T08146,"Bonington, Richard Parkes",artist,41,"Verona, Piazza dell’Erbe",c.1826–7,Watercolour and graphite on paper,Purchased as part of the Oppé Collection with ...,1826.0,1996.0,support: 206 x 265 mm,206,265,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/T/T08/T...,http://www.tate.org.uk/art/artworks/bonington-...
64455,23290,T09090,"Mulready, William",artist,392,"Playground Scene, Children Playing and Wrestling",1826,Ink on paper,Purchased as part of the Oppé Collection with ...,1826.0,1997.0,support: 139 x 112 mm,139,112,NaN,mm,date inscribed,NaN,http://www.tate.org.uk/art/images/work/T/T09/T...,http://www.tate.org.uk/art/artworks/mulready-p...
64461,23289,T09096,"Mulready, William",artist,392,Women and Children Listening to a Seated Man,1826,Ink on paper,Purchased as part of the Oppé Collection with ...,1826.0,1997.0,support: 54 x 52 mm,54,52,NaN,mm,date inscribed,NaN,http://www.tate.org.uk/art/images/work/T/T09/T...,http://www.tate.org.uk/art/artworks/mulready-w...

In [83]:
df.loc[df.dimension.str.contains('support')]

AttributeError: 'DataFrame' object has no attribute 'dimension'

In [85]:
df.loc[df.dimensions.str.contains('support', na=False)]

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
2,1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785.0,1922.0,support: 343 x 467 mm,343,467,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
3,1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 318 x 394 mm,318,394,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
32,1067,A00033,"Blake, William",artist,39,Sketch for ‘The Four and Twenty Elders Casting...,"c.1803, c.1805–10",Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1803.0,1922.0,support: 488 x 389 mm,488,389,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-sket...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69170,121195,T13839,"Barlow, Phyllida",artist,10908,Untitled,2003,Acrylic paint on paper,Presented by the Trustees of the Chantrey Bequ...,2003.0,2013.0,support: 560 x 762 mm,560,762,NaN,mm,NaN,© Phyllida Barlow,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/barlow-unt...
69171,121196,T13840,"Barlow, Phyllida",artist,10908,Untitled,2003,Acrylic paint on paper,Presented by the Trustees of the Chantrey Bequ...,2003.0,2013.0,support: 558 x 760 mm,558,760,NaN,mm,NaN,© Phyllida Barlow,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/barlow-unt...
69172,121197,T13841,"Barlow, Phyllida",artist,10908,Untitled,2004,Acrylic paint on paper,Presented by the Trustees of the Chantrey Bequ...,2004.0,2013.0,support: 380 x 566 mm,380,566,NaN,mm,NaN,© Phyllida Barlow,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/barlow-unt...
69173,121198,T13842,"Barlow, Phyllida",artist,10908,Untitled,2006,Acrylic paint on paper,Presented by the Trustees of the Chantrey Bequ...,2006.0,2013.0,support: 560 x 762 mm,560,762,NaN,mm,NaN,© Phyllida Barlow,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/barlow-unt...
69178,121565,T13847,"Walker, Kelley",artist,16207,Will We Ever Kill The Bug,2010,2 screenprints on fibreboard,Presented by Thomas Dane 2012,2010.0,2013.0,"support, each: 438 x 330 mm",NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/walker-wil...